import {
  FaGithub,
  FaReact,
  FaNodeJs,
  FaJava,
  FaPython,
  FaCss3Alt,
  FaCreditCard,
  FaChartLine,
  FaChartBar,
  FaWindows,
  FaMicrosoft,
} from "react-icons/fa6";

import {
  SiVite,
  SiExpo,
  SiExpress,
  SiFastapi,
  SiSpringboot,
  SiSpringsecurity,
  SiThymeleaf,
  SiTensorflow,
  SiScikitlearn,
  SiPandas,
  SiNumpy,
  SiStreamlit,
  SiMysql,
  SiMongodb,
  SiJsonwebtokens,
  SiGooglegemini,
  SiVercel,
  SiGooglemaps,
  SiNetlify,
  SiPostman,
  SiIntellijidea,
  SiUbuntu,
  SiArduino,
  SiRstudioide,
  SiFigma,
  SiPhp,
  SiRailway,
} from "react-icons/si";

import {
  TbBrandReactNative,
  TbCpu,
  TbBroadcast,
  TbBinaryTree,
  TbBrandVscode,
} from "react-icons/tb";

export const skill = {
  React: <FaReact className="w-6 h-6" />,
  "React Native": <TbBrandReactNative className=" w-6 h-6" />,
  Vite: <SiVite className=" w-6 h-6" />,
  Expo: <SiExpo className=" w-6 h-6" />,
  Express: <SiExpress className=" w-6 h-6" />,
  FastAPI: <SiFastapi className=" w-6 h-6" />,
  "Node.js": <FaNodeJs className=" w-6 h-6" />,
  Java: <FaJava className=" w-6 h-6" />,
  "Spring Boot": <SiSpringboot className=" w-6 h-6" />,
  "Spring Security": <SiSpringsecurity className=" w-6 h-6" />,
  Thymeleaf: <SiThymeleaf className=" w-6 h-6" />,
  Python: <FaPython className=" w-6 h-6" />,
  TensorFlow: <SiTensorflow className=" w-6 h-6" />,
  "scikit-learn": <SiScikitlearn className=" w-6 h-6" />,
  Pandas: <SiPandas className=" w-6 h-6" />,
  NumPy: <SiNumpy className=" w-6 h-6" />,
  XGBoost: <TbBinaryTree className=" w-6 h-6" />,
  Matplotlib: <FaChartLine className=" w-6 h-6" />,
  Seaborn: <FaChartBar className=" w-6 h-6" />,
  Streamlit: <SiStreamlit className=" w-6 h-6" />,
  MySQL: <SiMysql className=" w-6 h-6" />,
  MongoDB: <SiMongodb className=" w-6 h-6" />,
  JWT: <SiJsonwebtokens className=" w-6 h-6" />,
  CSS: <FaCss3Alt className=" w-6 h-6" />,
  "Gemini API": <SiGooglegemini className=" w-6 h-6" />,
  PayHere: <FaCreditCard className=" w-6 h-6" />,
  "Groq SDK": <TbCpu className=" w-6 h-6" />,
  SSE: <TbBroadcast className=" w-6 h-6" />,
  CatBoost: <TbBinaryTree className=" w-6 h-6" />,
  Git: <FaGithub className=" w-6 h-6" />,
  "GoogleMaps API": <SiGooglemaps className=" w-6 h-6" />,
  Vercel: <SiVercel className=" w-6 h-6" />,
  Railway: <SiRailway className=" w-6 h-6" />,
  Netify: <SiNetlify className=" w-6 h-6" />,
  Postman: <SiPostman className=" w-6 h-6" />,
  VSCode: <TbBrandVscode className=" w-6 h-6" />,
  IntelJ: <SiIntellijidea className=" w-6 h-6" />,
  Windows: <FaWindows className=" w-6 h-6" />,
  Ubuntu: <SiUbuntu className=" w-6 h-6" />,
  Ardino: <SiArduino className=" w-6 h-6" />,
  Rtudio: <SiRstudioide className=" w-6 h-6" />,
  "micrisoft 365": <FaMicrosoft className=" w-6 h-6" />,
  Figma: <SiFigma className=" w-6 h-6" />,
  "PHP  ": <SiPhp className=" w-6 h-6" />,
};
